services:
  vllm:
    # image: public.ecr.aws/q9t5s3a7/vllm-arm64-cpu-release-repo:v0.16.0-upgraded-transformers
    image: public.ecr.aws/q9t5s3a7/vllm-arm64-cpu-release-repo:v0.16.0
    privileged: true
    shm_size: 2gb
    container_name: vllm
    ports:
      - 8000:80
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/vllm/.cache:/root/.cache
    restart: unless-stopped
    entrypoint: |
      vllm serve Qwen/Qwen3-0.6B
        --reasoning-parser deepseek_r1
        --max-model-len 512
        --max-num-seqs 1
        --max-num-batched-tokens 256
        --enable-chunked-prefill
        --port 80
